export const mainCarouselData=[
    {
        image:"https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_0.jpg",
        path:"/woman/clothing/women_dress"
    },
    {
        image:"https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_1.jpg",
        path:"/woman/clothing/women_dress"
    },
    {
        image:"https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_2.jpg",
        path:"/woman/clothing/women_dress"
    },
    {
        image:"https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_3.jpg",
        path:"/woman/clothing/women_dress"
    },
    {
        image:"https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_4.jpg",
        path:"/woman/clothing/women_dress"
    },
]